[project]
name = "blue"
version = "0.9.3"
dependencies = [
    "setuptools",
    "black~=25.9.0",
    "click<8.2",
    "doc8",
    "twine",
    "wheel",
]
dynamic = ["readme", "description"]

[dependency-groups]
dev = [
    "flake8>=3.8",
    "pytest",
    "pytest-cov",
    "rstcheck",
    "sphinx",
    "tox",
]

[tool.uv]
package = false

[tool.ruff]
target-version = 'py312'
