[project]
name = 'blue'
version = '0.9.4'
requires-python = ">=3.12"
dependencies = [
    'setuptools',
    'black~=24.10.0',
    'click<8.2',
    'doc8',
    'twine',
    'wheel',
]
dynamic = ['readme', 'description']

[dependency-groups]
dev = [
    'flake8>=3.8',
    'pytest',
    'pytest-cov',
    'rstcheck',
    'sphinx',
    'tox',
]

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.blue]
line-length = 79
target-version = ['py312']

[tool.uv]
package = true

[tool.ruff]
target-version = 'py312'

[project.scripts]
blue = 'blue:main'
