[project]
name = 'blue'
version = '0.9.4'
requires-python = ">=3.10,<3.13"
dependencies = [
    'setuptools~=82.0.0',
    'black~=23.12.0',
    'click<8.2.0',  # avoid https://github.com/pallets/click/pull/2397
    'doc8~=2.0.0',
    'twine~=6.2.0',
    'wheel~=0.46.3',
]
dynamic = ['readme', 'description']

[dependency-groups]
dev = [
    'flake8',
    'pytest',
    'pytest-cov',
    'rstcheck',
    'sphinx',
    'tox',
]

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.blue]
line-length = 79
target-version = ['py312']

[tool.uv]
package = true

[tool.ruff]
target-version = 'py312'

[project.scripts]
blue = 'blue:main'
